### ISSUE TITLE
Should run-linux.sh use "java" instead of "javaw"?

### ISSUE THREAD

**Issue by rogerm4242** [HiranChaudhuri/OoliteStarter#10] opened 2023-08-22 21:45 UTC
**Describe the bug**
Should run-linux.sh use "java" instead of "javaw"? To the best of my knowledge this link shows why it would be better to use "java":  https://stackoverflow.com/questions/14331406/why-javaw-is-not-found-on-my-java-installation-on-ubuntu

**To Reproduce**
1. From a terminal prompt in the OoliteStarter folder, execute run.sh or run-linux.sh
2. Error:   "javaw: command not found"

**Expected behavior**
OoliteStarter should open

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 with OpenJDK 18
 - OS: Arch linux with OpenJDK 20
 - OoliteStarter version 0.1.18

**Comment by HiranChaudhuri** [comment] 2023-08-25 17:26
Your change looks good and it is merged. Thank you for pointing it out.
Is the intended behaviour now reproducible?

**Comment by rogerm4242** [comment] 2023-08-25 18:09
I am afraid I do not have a java development environment set up to build/compile the project to fully test this.

I simply edited the shell script with a text editor on my 2 linux boxes. Changing "javaw" to "java" made everything work on both systems for me.

BTW, Thanks for your work on this project. I am a new player enjoying Oolite!

**Comment by HiranChaudhuri** [comment] 2023-08-25 18:12
There is no need to setup a dev environment. I 4-eyed your change and found it good. Since I merged the new version got built automatically. So you might want to download OoliteStarter 0.1.19 just to verify your change still looks as intended. If it does we can close the issue.

Happy to hear you are having fun!

**Comment by rogerm4242** [comment] 2023-08-25 18:25
OK, thank for pointing that out.

I downloaded  OoliteStarter-0.1.19-generic.tar.gz and extracted it on my Ubuntu 22.04 system and the included run.sh launched correctly for me.

**Comment by HiranChaudhuri** [comment] 2023-08-25 18:27
Thank you for that confirmation. I will close the issue then. :-)

**Closed by HiranChaudhuri** 2023-08-25 18:27 UTC
Labels: bug
